@startuml

class Programme {
    String cheminEntree
    String cheminSortie
    Programme(String entree, String sortie)
    void setAlgorithmeResolution(AlgorithmeResolution ar)
    int ajouterIngredient(String ingredient)
    void ajouterClient(Client c)
    List<String> getIngredientsSolution()
    void trouverSolution(String cheminFichier)
    String getIngredient(int indexIngredient)
    int getNbIngredients()
    List<Client> getClients()
}
Programme --"*" Client: clients
Programme --"1" List<String>: ingredients
Programme --"1" List<String>: ingredientsSolution
Programme --"1" GestionnaireFichier: gestionFichier
Programme --"1" AlgorithmeResolution: resolveur

class GestionnaireFichier {
    GestionnaireFichier(Programme p)
    void getDonnees(String nomFichier)
    void ecrireResultat(String nomFichier)
    int getInt(String texte, String message)
    void ajouterClient(int noClient, String ligne1, String ligne2)
}
GestionnaireFichier --"1" Programme

abstract class AlgorithmeResolution {
    AlgorithmeResolution(Programme p)
    abstract Recette trouverSolution()
    int calculerScore(String codeRecette)
}
AlgorithmeResolution --"1" Programme: programme

class BranchAndBound extends AlgorithmeResolution {
    BranchAndBound(Programme p)
    Recette trouverSolution()
}

class ExplorationTotale extends AlgorithmeResolution {
    ExplorationTotale(Programme p)
    Recette trouverSolution()
}

class Genetique extends AlgorithmeResolution {
    int taillePopulation
    Genetique(Programme p, int taillePopulation)
    void trouverSolution()
    Dict<String, int> genererPopulation(int taille, int nbIngredients)
    List<String> selection(Dict<String, int> population, int nbSelection)
    List<String> croisement(List<String> recettesSelectionnes, int nbIndividus)
    List<String> mutation(List<String> enfants)
    Dict<String,int> evaluation(List<String>)
}

class Tabou extends AlgorithmeResolution {
    int tailleMemoire
    int nbMouvements
    Tabou(programme p, int tailleMemoire, int nbMouvements)
    void trouverSolution()
    String genererConfiguration(int nbIngredients)
    Dict<String, int> genererVoisins(int nbMouvements)
    Dict<String, int> getMeilleurVoisin()



}

class Recette {
    List<int> indexIngredients
    Set recetteSet
    Recette(Programme p, List<int> indexIngredients)
    Recette(Programme p, String codeIngredients)
    List<int> getIndexIngredients()
}
Recette --"1" Programme

class Client {
    int numero
    List<int> ingredientsAimes
    List<int> ingredientNonAimes
    Set ingredientsAimesSet
    Set ingredientsNonAimesSet

    Client(Programme p, int numero)
    void addIngredientAime(int indexIngredient)
    void addIngredientNonAime(int indexIngredient)
    booleen aime(int indexIngredient)
    booleen aimePas(int indexIngredient)
    booleen recetteAcceptable(Recette r)
}
Client --"1" Programme

@enduml